### ISSUE TITLE
React.addons.classSet has been deprecated.

### ISSUE THREAD

**Issue by sarahkirby** [anorudes/React-Scroll-Effect#2]
Hi there,

Wanting to use this package with React v15.0.1, however I'm unable to do so as React.addons.classSet has been deprecated.

Any help would be really appreciated.

Thanks,

Sarah

**Comment by ArnaudValensi** [comment]
Hi,

I've modified the component to work with React v15.1.0.

https://gist.github.com/ArnaudValensi/eef95545cb8a47b5d54887f41edd3430

I'm using it in a project, sorry I don't have the time to do a pull request.

Alternatively, you can use https://github.com/jlmakes/scrollreveal.js
I explain how to use it with React here https://github.com/jlmakes/scrollreveal.js/issues/218

**Comment by siemya** [comment]
@ArnaudValensi hey, i am using the modified component but doesnt work on ie. #6

**Comment by harrington101** [comment]
To fix it in IE try adding this to handleScroll()
`const scrollPositionY = window.scrollY ? window.scrollY : window.pageYOffset;`

**Comment by harrington101** [comment]
I do still have an IE issue though where the animations stop happening about half way down the page.

**Comment by anorudes** [comment]
I'm sorry, this package created about 2 years ago. I want to rewrite all, but not have the time. I have now accepted the last PR for react 15 version,

**Comment by harrington101** [comment]
This is fixed in the latest pull request.
